### PR TITLE
Upgraded to be compatible with latest Firebase Admin SDK

### PR DESCRIPTION
**Pull request by jwngr**
* Switched `ref()` to `ref` and `key()` to `key`.
* Added `firebase-admin` as a peer dependency.
* Removed unnecessary dependency on NodeFire and moved it to a peer dependency.
* Upgraded license year to 2018.
* Bumped version number to `1.0.0`.

---
This change is [Reviewable](https://reviewable.io/reviews/pkaminski/firelease/4)

### CODE REVIEW

**Review by jwngr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pkaminski/firelease/4)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @pkaminski)

___
*[package.json, line 34 at r1](https://reviewable.io/reviews/pkaminski/firelease/4#-LLiYwHR9LPrelJ9wnLO:-LLiYwHR9LPrelJ9wnLP:b-2kp1z7) ([raw file](https://github.com/pkaminski/firelease/blob/5efc05237d975f7aba0a68438fc1afd4daed4fe2/package.json#L34)):*
> ```JSON
>   },
>   "peerDependencies": {
>     "nodefire": "^1.0.0",
> ```

NodeFire hasn't been updated to `1.0.0` yet, so we likely will want to hold off on merging this in until that happens first.

**Review by pkaminski — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pkaminski/firelease/4)* status: all files reviewed, 2 unresolved discussions (waiting on @jwngr)

___
*[package.json, line 34 at r1](https://reviewable.io/reviews/pkaminski/firelease/4#-LLiYwHR9LPrelJ9wnLO:-LLksGzn8r724pMis5X0:b32w0x) ([raw file](https://github.com/pkaminski/firelease/blob/5efc05237d975f7aba0a68438fc1afd4daed4fe2/package.json#L34)):*
<details><summary><i>Previously, jwngr (Jacob Wenger) wrote…</i></summary><blockquote>

NodeFire hasn't been updated to `1.0.0` yet, so we likely will want to hold off on merging this in until that happens first.
</blockquote></details>

OK
___
*[package.json, line 35 at r1](https://reviewable.io/reviews/pkaminski/firelease/4#-LLks5L07mLm-ve9RHO6:-LLks5L07mLm-ve9RHO7:bs776uz) ([raw file](https://github.com/pkaminski/firelease/blob/5efc05237d975f7aba0a68438fc1afd4daed4fe2/package.json#L35)):*
> ```JSON
>   "peerDependencies": {
>     "nodefire": "^1.0.0",
>     "firebase-admin": "5.x.x || 6.x.x"
> ```

Given the dependency on `nodefire`, is the one on `firebase-admin` needed?  I think it should be up to `nodefire` alone to decide which SDK versions it's compatible with.

**Review by jwngr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pkaminski/firelease/4)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @pkaminski and @jwngr)

___
*[package.json, line 35 at r1](https://reviewable.io/reviews/pkaminski/firelease/4#-LLks5L07mLm-ve9RHO6:-LLnW_UtABtZRjc7nGbQ:bae0d96) ([raw file](https://github.com/pkaminski/firelease/blob/5efc05237d975f7aba0a68438fc1afd4daed4fe2/package.json#L35)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Given the dependency on `nodefire`, is the one on `firebase-admin` needed?  I think it should be up to `nodefire` alone to decide which SDK versions it's compatible with.
</blockquote></details>

Yup, that's a good point. I removed `firebase-admin` as a peer dep.

**Review by pkaminski — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pkaminski/firelease/4)* status: all files reviewed, 1 unresolved discussion (waiting on @jwngr)

**Pull request closed without merging**
